# Generated by Django 4.1 on 2022-08-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('surnames', models.CharField(max_length=256)),
                ('pwd', models.CharField(max_length=8)),
            ],
        ),
    ]
