# Generated by Django 4.1 on 2022-08-18 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('register_number', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=7)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('buy_date', models.DateField()),
                ('build_date', models.DateField()),
                ('kilometers', models.PositiveIntegerField()),
                ('proprietary', models.CharField(max_length=255)),
                ('passenger_number', models.PositiveIntegerField()),
                ('video', models.BooleanField(default=False)),
                ('wheel_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proprietary',
            fields=[
                ('nif', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surnames', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('register_number', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=7)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('buy_date', models.DateField()),
                ('build_date', models.DateField()),
                ('kilometers', models.PositiveIntegerField()),
                ('proprietary', models.CharField(max_length=255)),
                ('tara', models.PositiveIntegerField()),
                ('max_auth_load', models.PositiveIntegerField()),
                ('wheel_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('register_number', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=7)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('buy_date', models.DateField()),
                ('build_date', models.DateField()),
                ('kilometers', models.PositiveIntegerField()),
                ('proprietary', models.CharField(max_length=255)),
                ('load_volume', models.PositiveIntegerField()),
                ('load_length', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField(default=datetime.date(2022, 8, 18))),
                ('done_work', models.TextField()),
                ('price', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.bus')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.truck')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.van')),
            ],
        ),
    ]
