# Generated by Django 4.1 on 2022-08-18 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 18, 55, 43, 103280, tzinfo=datetime.timezone.utc)),
        ),
    ]
