# Generated by Django 4.1 on 2022-08-18 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_maintenance_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='proprietary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.proprietary'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 19, 2, 16, 401429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='truck',
            name='proprietary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.proprietary'),
        ),
        migrations.AlterField(
            model_name='van',
            name='proprietary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.proprietary'),
        ),
    ]
